import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { test } from 'node:test';

const requestsPageSource = readFileSync(new URL('./RequestsPage.vue', import.meta.url), 'utf8');
const detailsModalSource = readFileSync(new URL('./common/RequestDetailsModal.vue', import.meta.url), 'utf8');
const requestPosterCardSource = readFileSync(new URL('./common/RequestPosterCard.vue', import.meta.url), 'utf8');
const seerActionsSource = readFileSync(new URL('../composables/useRequestSeerActions.js', import.meta.url), 'utf8');
const traktActionsSource = readFileSync(new URL('../composables/useRequestTraktActions.js', import.meta.url), 'utf8');

test('request details modal renders Seer actions for selected and related requests', () => {
  assert.match(requestsPageSource, /:seer-modal-target="getSeerModalTarget\(selectedSource\)"/);
  assert.match(requestsPageSource, /:can-show-related-seer="canShowRelatedSeer"/);
  assert.match(requestsPageSource, /@approve-related-seer="approveFor"/);
  assert.match(requestsPageSource, /@decline-related-seer="declineFor"/);
  assert.match(seerActionsSource, /getRequestSeerStatusesBatch/);
  assert.match(seerActionsSource, /approveSeerRequest/);
  assert.match(seerActionsSource, /declineSeerRequest/);

  assert.match(detailsModalSource, /v-if="seerModalTarget" class="[^"]*seer-action-strip/);
  assert.match(detailsModalSource, /v-if="canShowRelatedSeer\(request\)" class="seer-inline-actions"/);
  assert.match(detailsModalSource, /data-testid="seer-action-strip"/);
  assert.match(detailsModalSource, /data-testid="seer-approve"/);
  assert.match(detailsModalSource, /data-testid="seer-decline"/);
  assert.match(detailsModalSource, /@click\.stop="\$emit\('approve-related-seer', request\)"/);
  assert.match(detailsModalSource, /seerRequestActions\.css/);
  assert.match(requestPosterCardSource, /data-testid="seer-poster-actions"/);
  assert.match(requestPosterCardSource, /data-testid="seer-poster-approve"/);
  assert.match(requestPosterCardSource, /seer-poster-dock/);
  assert.match(requestsPageSource, /useRequestSeerActions/);
  assert.match(requestsPageSource, /posterSeerProps/);
  assert.match(requestsPageSource, /await this\.prefetchRequestIntegrationStatusesAsync\(mapped\)/);
  assert.match(requestsPageSource, /Could not prefetch request integration statuses/);
  assert.match(requestsPageSource, /refreshModalIntegrationStatuses/);
  assert.match(requestsPageSource, /loadSeerStatusForSource\(source, \{ force: true \}\)/);
  assert.match(requestsPageSource, /loadSeerStatusFor\(request, \{ force: true \}\)/);
  assert.match(seerActionsSource, /const overflow = allPending\.slice\(POSTER_BATCH_SIZE\)/);
  assert.match(traktActionsSource, /const overflow = \[\]/);
  assert.match(traktActionsSource, /overflow\.push\(item\)/);
  assert.match(seerActionsSource, /stored !== resolved\.seer_status/);
  assert.match(seerActionsSource, /return item\?\.seer_status === 'pending'/);
  assert.match(seerActionsSource, /setSeerStatusChangeHandler/);
  assert.match(requestsPageSource, /seer_status: request\.seer_status/);
  assert.doesNotMatch(requestsPageSource, /@visible="onRequestCardVisible"/);
  assert.match(requestsPageSource, /seerStatusFilter/);
  assert.match(requestsPageSource, /SEER_STATUS_FILTER_OPTIONS/);
  assert.match(requestsPageSource, /refreshSeerFilterStatuses/);
  assert.match(requestsPageSource, /appliedSeerStatusFilter/);
  assert.match(requestsPageSource, /allRequestsHaveFreshSeerStatus/);
  assert.match(requestsPageSource, /isSeerBusy\(request\)/);
  assert.match(requestsPageSource, /filterIntegrationLoading/);
});
